#!/usr/bin/env python
# -*-python-*-

import sys
import os.path
import logging
import geojson
import mapzen.whosonfirst.geojson

if __name__ == '__main__':

    import optparse

    opt_parser = optparse.OptionParser("""wof-validate --options /path/to/wof-data""")

    opt_parser.add_option('-p', '--precision', dest='precision', action='store', default=None, help='Trim coordinates to this many decimal places (default is None)')
    opt_parser.add_option('--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')

    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    e = mapzen.whosonfirst.geojson.encoder(precision=options.precision)

    for path in args:

      path = os.path.abspath(path)

      fh = open(path, 'r')
      f = geojson.load(fh)

      e.encode_feature(f, sys.stdout)
      
    sys.exit()
